INSERT INTO "oregon_cities"("city")
VALUES
    ("Ada"),
    ("Adair Village"),
    ("Adams"),
    ("Adel"),
    ("Adrian"),
    ("Ady"),
    ("Agate Beach"),
    ("Agness"),
    ("Airlie"),
    ("Albany"),
    ("Albina"),
    ("Alder"),
    ("Alfalfa"),
    ("Algoma"),
    ("Alicel"),
    ("Allegany"),
    ("Alma"),
    ("Aloha"),
    ("Alpine"),
    ("Alsea"),
    ("Altamont"),
    ("Alvadore"),
    ("Amity"),
    ("Andrews"),
    ("Anlauf"),
    ("Antelope"),
    ("Antone"),
    ("Apiary"),
    ("Applegate"),
    ("Arago"),
    ("Arch Cape"),
    ("Arlington"),
    ("Arock"),
    ("Ash"),
    ("Ashland"),
    ("Ashwood"),
    ("Astoria"),
    ("Athena"),
    ("Auburn"),
    ("Aumsville"),
    ("Aurora"),
    ("Austa"),
    ("Austin"),
    ("Austin Junction"),
    ("Azalea"),
    ("Bacona"),
    ("Baker City"),
    ("Ballston"),
    ("Bandon"),
    ("Banks"),
    ("Barlow"),
    ("Barton"),
    ("Barview"),
    ("Bates"),
    ("Bay City"),
    ("Bayocean"),
    ("Beatty"),
    ("Beaver"),
    ("Beavercreek"),
    ("Beaver Hill"),
    ("Beaver Marsh"),
    ("Beaverton"),
    ("Beech Creek"),
    ("Belknap Springs"),
    ("Bellevue"),
    ("Bellfountain"),
    ("Bend"),
    ("Bethany"),
    ("Bethel"),
    ("Beulah"),
    ("Beverly Beach"),
    ("Biggs Junction"),
    ("Bingham Springs"),
    ("Birkenfeld"),
    ("Blachly"),
    ("Black Butte Ranch"),
    ("Black Rock"),
    ("Blakeley"),
    ("Blalock"),
    ("Blodgett"),
    ("Blooming"),
    ("Blue River"),
    ("Bly"),
    ("Boardman"),
    ("Bonanza"),
    ("Bonita"),
    ("Bonneville"),
    ("Bonny Slope"),
    ("Boring"),
    ("Bourne"),
    ("Boyd"),
    ("Breitenbush"),
    ("Brickerville"),
    ("Bridal Veil"),
    ("Bridge"),
    ("Bridgeport"),
    ("Brighton"),
    ("Brightwood"),
    ("Broadbent"),
    ("Brockway"),
    ("Brogan"),
    ("Brookings"),
    ("Brooks"),
    ("Brothers"),
    ("Brownlee"),
    ("Brownsmead"),
    ("Brownsville"),
    ("Buchanan"),
    ("Buena Vista"),
    ("Bull Mountain"),
    ("Bull Run"),
    ("Buncom"),
    ("Bunker Hill"),
    ("Burlington"),
    ("Burns"),
    ("Burns Junction"),
    ("Burnt Woods"),
    ("Butte Falls"),
    ("Butteville"),
    ("Buxton"),
    ("Cabell City"),
    ("Cairo"),
    ("Camas Valley"),
    ("Camp Sherman"),
    ("Canary"),
    ("Canby"),
    ("Canemah"),
    ("Cannon Beach"),
    ("Canyon City"),
    ("Canyonville"),
    ("Cape Meares"),
    ("Carlton"),
    ("Carnation"),
    ("Carpenterville"),
    ("Carson"),
    ("Carus"),
    ("Carver"),
    ("Cascade Locks"),
    ("Cascade Summit"),
    ("Cascadia"),
    ("Castle Rock"),
    ("Cave Junction"),
    ("Cayuse"),
    ("Cazadero"),
    ("Cecil"),
    ("Cedar Hills"),
    ("Cedar Mill"),
    ("Celilo Village"),
    ("Central Point"),
    ("Champoeg"),
    ("Charbonneau"),
    ("Charleston"),
    ("Chehalem"),
    ("Chemawa"),
    ("Chemult"),
    ("Cherry Grove"),
    ("Cherryville"),
    ("Cheshire"),
    ("Chiloquin"),
    ("Chitwood"),
    ("Christmas Valley"),
    ("Clackamas"),
    ("Clarno"),
    ("Clatskanie"),
    ("Clear Lake"),
    ("Clem"),
    ("Clifton"),
    ("Cloverdale"),
    ("Coburg"),
    ("Cold Springs"),
    ("Colton"),
    ("Columbia City"),
    ("Condon"),
    ("Coos Bay"),
    ("Cooston"),
    ("Copper"),
    ("Copperfield"),
    ("Coquille"),
    ("Corbett"),
    ("Cornelius"),
    ("Cornucopia"),
    ("Corvallis"),
    ("Cottage Grove"),
    ("Cottrell"),
    ("Courtrock"),
    ("Cove"),
    ("Crabtree"),
    ("Crane"),
    ("Crawfordsville"),
    ("Crescent"),
    ("Crescent Lake"),
    ("Crescent Lake Junction"),
    ("Creswell"),
    ("Crooked River Ranch"),
    ("Crow"),
    ("Crowley"),
    ("Culp Creek"),
    ("Culver"),
    ("Curtin"),
    ("Cushman"),
    ("Cutler City"),
    ("Dairy"),
    ("Dale"),
    ("Dallas"),
    ("Damascus"),
    ("Danner"),
    ("Dawson"),
    ("Days Creek"),
    ("Dayton"),
    ("Dayville"),
    ("Deadwood"),
    ("Dee"),
    ("Deerhorn"),
    ("Deer Island"),
    ("Delake"),
    ("Dellwood"),
    ("Denio"),
    ("Denmark"),
    ("Depoe Bay"),
    ("Detroit"),
    ("Dexter"),
    ("Diamond"),
    ("Diamond Lake"),
    ("Dillard"),
    ("Dilley"),
    ("Disston"),
    ("Divide"),
    ("Dixie"),
    ("Dodson"),
    ("Dolph"),
    ("Donald"),
    ("Donnybrook"),
    ("Dora"),
    ("Dorena"),
    ("Drain"),
    ("Drew"),
    ("Drewsey"),
    ("Dryden"),
    ("Dufur"),
    ("Dundee"),
    ("Dunes City"),
    ("Dunthorpe"),
    ("Durham"),
    ("Durkee"),
    ("Eagle Creek"),
    ("Eagle Point"),
    ("East Portland"),
    ("Eastside"),
    ("Echo"),
    ("Eddyville"),
    ("Eightmile"),
    ("Elgin"),
    ("Elk City"),
    ("Elkhead"),
    ("Elkton"),
    ("Ella"),
    ("Ellendale"),
    ("Elmira"),
    ("Elmonica"),
    ("Elsie"),
    ("Empire"),
    ("Enterprise"),
    ("Eola"),
    ("Estacada"),
    ("Eugene"),
    ("Fairbanks"),
    ("Fairview"),
    ("Falcon Heights"),
    ("Fall Creek"),
    ("Falls City"),
    ("Farmington"),
    ("Ferndale"),
    ("Fields"),
    ("Finn Rock"),
    ("Fisher"),
    ("Five Corners"),
    ("Flagg"),
    ("Flavel"),
    ("Flora"),
    ("Florence"),
    ("Flynn"),
    ("Forest Grove"),
    ("Fort Klamath"),
    ("Fort Rock"),
    ("Fort Stevens"),
    ("Foss"),
    ("Fossil"),
    ("Foster"),
    ("Four Corners"),
    ("Fox"),
    ("Franklin"),
    ("Frankport"),
    ("Frenchglen"),
    ("Friend"),
    ("Galena"),
    ("Gales Creek"),
    ("Galice"),
    ("Garden Home–Whitford"),
    ("Gardiner"),
    ("Garibaldi"),
    ("Gaston"),
    ("Gates"),
    ("Gateway"),
    ("Gaylord"),
    ("Gearhart"),
    ("Gervais"),
    ("Gibbon"),
    ("Gilchrist"),
    ("Gillespie Corners"),
    ("Gladstone"),
    ("Glenada"),
    ("Glenbrook"),
    ("Glencoe"),
    ("Glendale"),
    ("Gleneden Beach"),
    ("Glenwood"),
    ("Glide"),
    ("Goble"),
    ("Gold Beach"),
    ("Golden"),
    ("Gold Hill"),
    ("Goldson"),
    ("Gopher"),
    ("Gopher Flats"),
    ("Goshen"),
    ("Government Camp"),
    ("Grand Ronde"),
    ("Granite"),
    ("Grants Pass"),
    ("Grass Valley"),
    ("Gravelford"),
    ("Green"),
    ("Green Acres"),
    ("Greenberry"),
    ("Greenhorn"),
    ("Greenleaf"),
    ("Greenville"),
    ("Gresham"),
    ("Hadleyville"),
    ("Hager"),
    ("Haines"),
    ("Halfway"),
    ("Halsey"),
    ("Hamilton"),
    ("Hamlet"),
    ("Hammond"),
    ("Hampton"),
    ("Happy Valley"),
    ("Harbor"),
    ("Hardman"),
    ("Harlan"),
    ("Harper"),
    ("Harris"),
    ("Harrisburg"),
    ("Hatfield"),
    ("Hauser"),
    ("Havana"),
    ("Hayward"),
    ("Hazeldale"),
    ("Hebo"),
    ("Heceta Beach"),
    ("Helix"),
    ("Helvetia"),
    ("Henley"),
    ("Heppner"),
    ("Hereford"),
    ("Hermiston"),
    ("Hildebrand"),
    ("Hilgard"),
    ("Hillsboro"),
    ("Hines"),
    ("Hinkle"),
    ("Holbrook"),
    ("Holdman"),
    ("Holland"),
    ("Holley"),
    ("Homestead"),
    ("Hood River"),
    ("Hopewell"),
    ("Horse Heaven"),
    ("Horton"),
    ("Hoskins"),
    ("Hot Lake"),
    ("Hubbard"),
    ("Huber"),
    ("Hugo"),
    ("Huntington"),
    ("Idanha"),
    ("Idaville"),
    ("Idiotville"),
    ("Idleyld Park"),
    ("Illahe"),
    ("Imbler"),
    ("Imnaha"),
    ("Independence"),
    ("Indian Village"),
    ("Indiola"),
    ("Inglis"),
    ("Inlow"),
    ("Interlachen"),
    ("Ione"),
    ("Ironside"),
    ("Irrigon"),
    ("Irving"),
    ("Island City"),
    ("Izee"),
    ("Jacksonville"),
    ("Jamieson"),
    ("Jasper"),
    ("Jean"),
    ("Jeffers Garden"),
    ("Jefferson"),
    ("Jennings Lodge"),
    ("Jewell"),
    ("Jewell Junction"),
    ("Jimtown"),
    ("John Day"),
    ("Johnson City"),
    ("Jonesboro"),
    ("Jordan"),
    ("Jordan Creek"),
    ("Jordan Valley"),
    ("Joseph"),
    ("Junction City"),
    ("Juntura"),
    ("Kamela"),
    ("Kansas City"),
    ("Keasey"),
    ("Keating"),
    ("Keizer"),
    ("Kellogg"),
    ("Kelso"),
    ("Keno"),
    ("Kent"),
    ("Kerby"),
    ("Kernville"),
    ("Kerry"),
    ("Kimberly"),
    ("King City"),
    ("Kingsley"),
    ("Kingston"),
    ("Kings Valley"),
    ("Kinton"),
    ("Kinzua"),
    ("Kirk"),
    ("Kirkpatrick"),
    ("Klamath Agency"),
    ("Klamath Falls"),
    ("Klondike"),
    ("Knappa"),
    ("Lacomb"),
    ("Ladd Hill"),
    ("Lafayette"),
    ("La Grande"),
    ("Lake Creek"),
    ("Lake Grove"),
    ("Lake Oswego"),
    ("Lakeside"),
    ("Lakeview"),
    ("Lakewood"),
    ("Lancaster"),
    ("Langell Valley"),
    ("Langlois"),
    ("La Pine"),
    ("Latham"),
    ("Laurel"),
    ("Laurel Grove"),
    ("Laurelwood"),
    ("Lawen"),
    ("Leaburg"),
    ("Lebanon"),
    ("Lees Camp"),
    ("Lehman Springs"),
    ("Leland"),
    ("Lemati"),
    ("Lena"),
    ("Leneve"),
    ("Lenz"),
    ("Leona"),
    ("Lewis"),
    ("Lewisburg"),
    ("Lewisville"),
    ("Lexington"),
    ("Libby"),
    ("Liberal"),
    ("Lime"),
    ("Lincoln Beach"),
    ("Lincoln City"),
    ("Lindbergh"),
    ("Linn City"),
    ("Linnton"),
    ("Linslaw"),
    ("Little Albany"),
    ("Little Alps"),
    ("Locust Grove"),
    ("Logan"),
    ("Logsden"),
    ("London Springs"),
    ("Lone Elder"),
    ("Lonerock"),
    ("Long Creek"),
    ("Lookingglass"),
    ("Lorane"),
    ("Lorella"),
    ("Lostine"),
    ("Lowell"),
    ("Low Pass"),
    ("Lukarilla"),
    ("Lunnville"),
    ("Luper"),
    ("Lyons"),
    ("Mabel"),
    ("Macksburg"),
    ("Macleay"),
    ("Madras"),
    ("Malabon"),
    ("Malin"),
    ("Malone"),
    ("Manhattan Beach"),
    ("Manning"),
    ("Manzanita"),
    ("Mapleton"),
    ("Marcola"),
    ("Marial"),
    ("Marion"),
    ("Marion Forks"),
    ("Marlene Village"),
    ("Marmot"),
    ("Marquam"),
    ("Marshland"),
    ("Marylhurst"),
    ("Maupin"),
    ("Maxville"),
    ("Mayger"),
    ("Mayville"),
    ("Maywood Park"),
    ("McCoy"),
    ("McCredie Springs"),
    ("McDermitt"),
    ("McDonald"),
    ("McEwen"),
    ("McKay"),
    ("McKee"),
    ("McKee Bridge"),
    ("McKenzie Bridge"),
    ("McKinley"),
    ("McLeod"),
    ("McMinnville"),
    ("McNary"),
    ("McNulty"),
    ("Meacham"),
    ("Meda"),
    ("Medford"),
    ("Medical Springs"),
    ("Mehama"),
    ("Melrose"),
    ("Melville"),
    ("Merlin"),
    ("Merrill"),
    ("Metolius"),
    ("Metzger"),
    ("Middle Grove"),
    ("Middleton"),
    ("Midland"),
    ("Midway"),
    ("Mikkalo"),
    ("Miles Crossing"),
    ("Mill City"),
    ("Millersburg"),
    ("Millican"),
    ("Millington"),
    ("Millwood"),
    ("Milo"),
    ("Milton-Freewater"),
    ("Milwaukie"),
    ("Milwaukie Heights"),
    ("Minam"),
    ("Minerva"),
    ("Mission"),
    ("Mist"),
    ("Mitchell"),
    ("Modeville"),
    ("Modoc Point"),
    ("Mohawk"),
    ("Mohler"),
    ("Molalla"),
    ("Molalla Prairie"),
    ("Monitor"),
    ("Monkland"),
    ("Monmouth"),
    ("Monroe"),
    ("Monument"),
    ("Morgan"),
    ("Moro"),
    ("Mosier"),
    ("Mountain Air Park"),
    ("Mountaindale"),
    ("Mountain View"),
    ("Mount Angel"),
    ("Mount Hood"),
    ("Mount Hood Village"),
    ("Mount Vernon"),
    ("Mulino"),
    ("Mulloy"),
    ("Murphy"),
    ("Myrick"),
    ("Myrtle Creek"),
    ("Myrtle Point"),
    ("Narrows"),
    ("Nashville"),
    ("Navy Heights"),
    ("Neahkahnie Beach"),
    ("Necanicum"),
    ("Nedonna Beach"),
    ("Needy"),
    ("Nehalem"),
    ("Nelscott"),
    ("Neotsu"),
    ("Nesika Beach"),
    ("Neskowin"),
    ("Netarts"),
    ("Newberg"),
    ("New Bridge"),
    ("New Era"),
    ("New Hope"),
    ("New Pine Creek"),
    ("Newport"),
    ("Newport Heights"),
    ("New Princeton"),
    ("Niagara"),
    ("Nibley"),
    ("Nimrod"),
    ("Nolin"),
    ("Nonpareil"),
    ("Noon"),
    ("North Albany"),
    ("North Beach"),
    ("North Bend"),
    ("North Howell"),
    ("North Plains"),
    ("North Powder"),
    ("Nortons"),
    ("Norway"),
    ("Norwood"),
    ("Noti"),
    ("Nye"),
    ("Nyssa"),
    ("Oak Grove"),
    ("Oak Hills"),
    ("Oakland"),
    ("Oakridge"),
    ("Oatfield"),
    ("O'Brien"),
    ("Oceanlake"),
    ("Ocean Park"),
    ("Oceanside"),
    ("Odell"),
    ("Odessa"),
    ("Olene"),
    ("Olex"),
    ("Olney"),
    ("Ontario"),
    ("Ophir"),
    ("Oregon City"),
    ("Orenco"),
    ("Oretown"),
    ("Orleans"),
    ("Orodell"),
    ("Ortley"),
    ("Otis"),
    ("Otis Junction"),
    ("Otter Rock"),
    ("Owyhee"),
    ("Oxbow"),
    ("Pacific City"),
    ("Paisley"),
    ("Paradise"),
    ("Parkdale"),
    ("Paulina"),
    ("Payette Junction"),
    ("Pedee"),
    ("Pelican City"),
    ("Pendleton"),
    ("Peoria"),
    ("Perry"),
    ("Perrydale"),
    ("Philomath"),
    ("Phoenix"),
    ("Pilot Rock"),
    ("Pine"),
    ("Pine Grove"),
    ("Pinehurst"),
    ("Pine Ridge"),
    ("Pistol River"),
    ("Pittsburg"),
    ("Placer"),
    ("Pleasant Hill"),
    ("Pleasant Valley"),
    ("Plush"),
    ("Pocahontas"),
    ("Pondosa"),
    ("Portland"),
    ("Port Orford"),
    ("Post"),
    ("Powell Butte"),
    ("Powers"),
    ("Prairie City"),
    ("Pratum"),
    ("Prescott"),
    ("Prineville"),
    ("Progress"),
    ("Prospect"),
    ("Prosper"),
    ("Provolt"),
    ("Quartz Mountain"),
    ("Quincy"),
    ("Rainbow"),
    ("Rainier"),
    ("Rajneeshpuram"),
    ("Raleigh Hills"),
    ("Range"),
    ("Redland"),
    ("Redmond"),
    ("Reedsport"),
    ("Reedville"),
    ("Remote"),
    ("Rhododendron"),
    ("Rice"),
    ("Rice Hill"),
    ("Richland"),
    ("Richmond"),
    ("Rickreall"),
    ("Riddle"),
    ("Rieth"),
    ("Riley"),
    ("Ripplebrook"),
    ("Ritter"),
    ("Rivergrove"),
    ("Riverside"),
    ("Riverton"),
    ("Riverview"),
    ("Riverwood"),
    ("Roads End"),
    ("Robinsonville"),
    ("Rockaway Beach"),
    ("Rockcreek"),
    ("Rock Creek"),
    ("Rock Point"),
    ("Rocky Point"),
    ("Rogue River"),
    ("Rome"),
    ("Roseburg"),
    ("Rosedale"),
    ("Rose Lodge"),
    ("Round Prairie"),
    ("Rowena"),
    ("Rowland"),
    ("Roy"),
    ("Ruch"),
    ("Rufus"),
    ("Ruggs"),
    ("Saginaw"),
    ("Saint Benedict"),
    ("Saint Helens"),
    ("Saint Johns"),
    ("Saint Joseph"),
    ("Saint Louis"),
    ("Saint Paul"),
    ("Salem"),
    ("Salisbury"),
    ("Salt Creek"),
    ("Sams Valley"),
    ("Sandy"),
    ("Santiam Junction"),
    ("Scappoose"),
    ("Scholls"),
    ("Scio"),
    ("Scottsburg"),
    ("Scotts Mills"),
    ("Seal Rock"),
    ("Searose Beach"),
    ("Seaside"),
    ("Sellwood"),
    ("Selma"),
    ("Seneca"),
    ("Service Creek"),
    ("Shadowood"),
    ("Shady"),
    ("Shady Cove"),
    ("Shaniko"),
    ("Shaw"),
    ("Shedd"),
    ("Sheridan"),
    ("Sherwood"),
    ("Shevlin"),
    ("Shipley"),
    ("Siletz"),
    ("Siltcoos"),
    ("Silver Lake"),
    ("Silverton"),
    ("Sisters"),
    ("Sitkum"),
    ("Sixes"),
    ("Skipanon"),
    ("Sodaville"),
    ("South Beach"),
    ("South Lebanon"),
    ("Southport"),
    ("Sparta"),
    ("Sprague River"),
    ("Spray"),
    ("Springbrook"),
    ("Springdale"),
    ("Springfield"),
    ("Springwater"),
    ("Stafford"),
    ("Stanfield"),
    ("Starkey"),
    ("Starvation Heights"),
    ("Stayton"),
    ("Steamboat"),
    ("Sterlingville"),
    ("Sublimity"),
    ("Sulphur Springs"),
    ("Summer Lake"),
    ("Summerville"),
    ("Summit"),
    ("Sumner"),
    ("Sumpter"),
    ("Sunnyside"),
    ("Sunny Valley"),
    ("Sunriver"),
    ("Sunset Beach"),
    ("Suplee"),
    ("Surf Pines"),
    ("Susanville"),
    ("Sutherlin"),
    ("Suver"),
    ("Svensen"),
    ("Sweet Home"),
    ("Swisshome"),
    ("Table Rock"),
    ("Taft"),
    ("Takilma"),
    ("Talbot"),
    ("Talent"),
    ("Tallman"),
    ("Tangent"),
    ("Telocaset"),
    ("Tenmile"),
    ("Terrebonne"),
    ("Thatcher"),
    ("The Dalles"),
    ("Thomas"),
    ("Three Rivers"),
    ("Thurston"),
    ("Tide"),
    ("Tidewater"),
    ("Tiernan"),
    ("Tierra Del Mar"),
    ("Tigard"),
    ("Tillamook"),
    ("Tiller"),
    ("Timber"),
    ("Toledo"),
    ("Tollgate"),
    ("Tolo"),
    ("Tolovana Park"),
    ("Tonquin"),
    ("Trail"),
    ("Triangle Lake"),
    ("Tri-City"),
    ("Troutdale"),
    ("Troy"),
    ("Tualatin"),
    ("Tumalo"),
    ("Turner"),
    ("Twickenham"),
    ("Twin Rocks"),
    ("Tygh Valley"),
    ("Ukiah"),
    ("Umapine"),
    ("Umatilla"),
    ("Umpqua"),
    ("Union"),
    ("Union Creek"),
    ("Unity"),
    ("Vale"),
    ("Valley Falls"),
    ("Valley Junction"),
    ("Valsetz"),
    ("Van"),
    ("Vanport"),
    ("Vaughn"),
    ("Venator"),
    ("Veneta"),
    ("Verboort"),
    ("Vernonia"),
    ("Vida"),
    ("Voltage"),
    ("Waconda"),
    ("Wagontire"),
    ("Walden"),
    ("Waldo"),
    ("Waldport"),
    ("Walker"),
    ("Wallowa"),
    ("Walterville"),
    ("Walton"),
    ("Wamic"),
    ("Wankers Corner"),
    ("Wapinitia"),
    ("Warm Springs"),
    ("Warren"),
    ("Warrendale"),
    ("Warrenton"),
    ("Wasco"),
    ("Waterloo"),
    ("Waterman"),
    ("Wauna"),
    ("Weatherby"),
    ("Wecoma Beach"),
    ("Wedderburn"),
    ("Welches"),
    ("Wemme"),
    ("Wendling"),
    ("Westfall"),
    ("Westfir"),
    ("West Haven-Sylvan"),
    ("West Linn"),
    ("Weston"),
    ("Westport"),
    ("West Salem"),
    ("West Scio"),
    ("West Side"),
    ("West Slope"),
    ("West Stayton"),
    ("West Union"),
    ("Wheatland"),
    ("Wheeler"),
    ("White City"),
    ("Whiteson"),
    ("Whitney"),
    ("Wilbur"),
    ("Wilderville"),
    ("Wilkesboro"),
    ("Willamette"),
    ("Willamina"),
    ("Williams"),
    ("Willowcreek"),
    ("Wilsonville"),
    ("Wimer"),
    ("Winchester"),
    ("Winchester Bay"),
    ("Wingville"),
    ("Winston"),
    ("Witch Hazel"),
    ("Wolf Creek"),
    ("Wonder"),
    ("Woodburn"),
    ("Woods"),
    ("Woodson"),
    ("Wood Village"),
    ("Worden"),
    ("Wren"),
    ("Wyeth"),
    ("Yachats"),
    ("Yamhill"),
    ("Yaquina"),
    ("Yarnell"),
    ("Yoder"),
    ("Yoncalla"),
    ("Yonna"),
    ("Zena"),
    ("Zigzag"),
    ("Zumwalt"),
    ("Westlake")
ON CONFLICT("id") DO NOTHING
;

INSERT INTO "oregon_city_spellings"(
    "city_id",
    "spelling"
) VALUES 
    ((select "id" from oregon_cities where city='Astoria'), 'astroia'),
    ((select "id" from oregon_cities where city='Beaverton'), 'beavteron'),
    ((select "id" from oregon_cities where city='Cottage Grove'), 'cottage grover'),
    ((select "id" from oregon_cities where city='Cave Junction'), 'cove junction'),
    ((select "id" from oregon_cities where city='Eugene'), 'euegene'),
    ((select "id" from oregon_cities where city='Gearhart'), 'gerhart'),
    ((select "id" from oregon_cities where city='Gladstone'), 'gladdstone'),
    ((select "id" from oregon_cities where city='Grants Pass'), 'grants pas'),
    ((select "id" from oregon_cities where city='La Grande'), 'lagrande'),
    ((select "id" from oregon_cities where city='La Pine'), 'la pien'),
    ((select "id" from oregon_cities where city='La Pine'), 'lapine'),
    ((select "id" from oregon_cities where city='Madra'), 'madrass'),
    ((select "id" from oregon_cities where city='Manzanita'), 'manzanta'),
    ((select "id" from oregon_cities where city='Medford'), 'medord'),
    ((select "id" from oregon_cities where city='Milton-Freewater'), 'milton freewater'),
    ((select "id" from oregon_cities where city='Milwaukie'), 'milwaukee'),
    ((select "id" from oregon_cities where city='Mount Angel'), 'mt angel'),
    ((select "id" from oregon_cities where city='Mount Vernon'), 'mt vernon'),
    ((select "id" from oregon_cities where city='Mount Vernon'), 'mt. vernon'),
    ((select "id" from oregon_cities where city='Myrtle Point'), 'mytle point'),
    ((select "id" from oregon_cities where city='Neotsu'), 'neostsu'),
    ((select "id" from oregon_cities where city='New Princeton'), 'princeton'),
    ((select "id" from oregon_cities where city='Redmond'), 'remdond'),
    ((select "id" from oregon_cities where city='Rockaway Beach'), 'rockaway'),
    ((select "id" from oregon_cities where city='Scappoose'), 'scapoose'),
    ((select "id" from oregon_cities where city='Scappoose'), 'scapppoose'),
    ((select "id" from oregon_cities where city='Shady Cove'), 'shadycove'),
    ((select "id" from oregon_cities where city='Sherwood'), 'shewood'),
    ((select "id" from oregon_cities where city='Sisters'), 'sister'),
    ((select "id" from oregon_cities where city='Saint Helens'), 'st helens'),
    ((select "id" from oregon_cities where city='Saint Helens'), 'st. helens'),
    ((select "id" from oregon_cities where city='Veneta'), 'venita')
    ;
